package xyz.byxor.hotkeys.keyboard

data class Key(
        val name: KeyName,
        val pressType: KeyPressType
)

enum class KeyName {
    ENTER,
    FORWARD_SLASH,
    BACKWARDS_SLASH,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    LOWERCASE_A,
    LOWERCASE_B,
    LOWERCASE_C,
    LOWERCASE_D,
    LOWERCASE_E,
    LOWERCASE_F,
    LOWERCASE_G,
    LOWERCASE_H,
    LOWERCASE_I,
    LOWERCASE_J,
    LOWERCASE_K,
    LOWERCASE_L,
    LOWERCASE_M,
    LOWERCASE_N,
    LOWERCASE_O,
    LOWERCASE_P,
    LOWERCASE_Q,
    LOWERCASE_R,
    LOWERCASE_S,
    LOWERCASE_T,
    LOWERCASE_U,
    LOWERCASE_V,
    LOWERCASE_W,
    LOWERCASE_X,
    LOWERCASE_Y,
    LOWERCASE_Z,

    UPPERCASE_A,
    UPPERCASE_B,
    UPPERCASE_C,
    UPPERCASE_D,
    UPPERCASE_E,
    UPPERCASE_F,
    UPPERCASE_G,
    UPPERCASE_H,
    UPPERCASE_I,
    UPPERCASE_J,
    UPPERCASE_K,
    UPPERCASE_L,
    UPPERCASE_M,
    UPPERCASE_N,
    UPPERCASE_O,
    UPPERCASE_P,
    UPPERCASE_Q,
    UPPERCASE_R,
    UPPERCASE_S,
    UPPERCASE_T,
    UPPERCASE_U,
    UPPERCASE_V,
    UPPERCASE_W,
    UPPERCASE_X,
    UPPERCASE_Y,
    UPPERCASE_Z
}

enum class KeyPressType {
    UP, DOWN, TYPED
}